name: Update README
on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Manual trigger option
  
  push:
    branches:
      - main

jobs:
  update-readme:
    permissions:
      contents: write  # Explicit permissions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          # Get current date
          DATE=$(date '+%Y-%m-%d')
          
          # Update last modified date in README
          sed -i "s/Last Updated: .*/Last Updated: $DATE/" README.md
          
          # Update profile views count
          sed -i "s/<p align=\"left\">.*profile%20views.*/<p align=\"left\"> <img src=\"https:\/\/komarev.com\/ghpvc\/?username=muzammil-13\&label=Profile%20views\&color=000000\&style=flat\" alt=\"muzammil-13\" \/> <\/p>/" README.md
          
          # Commit changes if any
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with latest info"
          git push